### ISSUE TITLE
Throws this error whenever I run the app

### ISSUE THREAD

**Issue by AdrianVovk** [plusCubed/recycler-fast-scroll#15]
Here is the logcat

`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference
                                                                     at android.support.v7.widget.RecyclerView.computeVerticalScrollOffset(RecyclerView.java:1613)
                                                                     at com.pluscubed.recyclerfastscroll.RecyclerFastScroller.onLayout(RecyclerFastScroller.java:384)`

**Comment by pluscubed** [comment]
From the logcat it looks like the LayoutManager is null. Does the RecyclerView have a LayoutManager attached?

**Comment by AdrianVovk** [comment]
@plusCubed I figured it out. DataBinding was throwing some issues with one of my adapters so I temporarily removed the code. It is fixed
