### ISSUE TITLE
Error on 0.3.1

### ISSUE THREAD

**Issue by limpmike** [plusCubed/recycler-fast-scroll#17]
Hello, when i update the library to the lastest version, it trows this error.

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView$Adapter.registerAdapterDataObserver(android.support.v7.widget.RecyclerView$AdapterDataObserver)' on a null object reference
                                                                         at com.pluscubed.recyclerfastscroll.RecyclerFastScroller.initRecyclerViewOnScrollListener(RecyclerFastScroller.java:342)
                                                                         at com.pluscubed.recyclerfastscroll.RecyclerFastScroller.attachRecyclerView(RecyclerFastScroller.java:307)`

on this line

`fastScroller.attachRecyclerView(rv);`

**Comment by pluscubed** [comment]
The RecyclerView's adapter must be attached when `attachRecyclerView()` is called
