### ISSUE TITLE
NPE at RecyclerFastScroller$3.onTouch

### ISSUE THREAD

**Issue by igozhenko** [plusCubed/recycler-fast-scroll#28]
Got several crashes at my project.

stacktrace
`at com.pluscubed.recyclerfastscroll.RecyclerFastScroller$3.onTouch(Unknown Source:151)
       at android.view.View.dispatchTouchEvent(View.java:8394)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2455)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2433)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2390)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1741)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2827)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source:71)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2351)
       at android.view.View.dispatchPointerEvent(View.java:8590)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4104)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3970)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3494)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3547)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3513)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3521)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3494)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3547)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3513)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3623)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3521)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3680)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3494)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3547)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3513)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3521)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3494)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5799)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5773)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5744)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5918)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:122)
       at android.app.ActivityThread.main(ActivityThread.java:5376)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)`

devices and os
![image](https://cloud.githubusercontent.com/assets/2979445/22908211/dd865f98-f255-11e6-9815-fcaf910815f5.png)

**Comment by emptyway** [comment]
Same here, happens when trying to swipe the NavigationView widget.

**Comment by CharlieReece** [comment]
This is still happening...

**Comment by CharlieReece** [comment]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.stopScroll()' on a null object reference
       at com.pluscubed.recyclerfastscroll.RecyclerFastScroller$3.onTouch(RecyclerFastScroller.java:151)
```
